=-*- mode: org; mode: visual-line;  -*-=
#+STARTUP: indent

* =zeroconf=

This is a release of Rémy Muller's zeroconf objects for MaxMSP. The sources are here, including projects for OS X (Xcode 3.2) and Windows (Visual Studio Express 2008).

Both builds are now current. The Xcode build creates Max externals as universal binaries, compatible with OS X 10.4 (Tiger) onwards.

* Usage

- The directory =cassiel.zeroconf= is laid out as a Max 7 package and contains everything *except* the native binaries, since those (at least on OS X) are bundles, and are rather untidy to check into Git directly. The zipped bundles are in folder =zipped-externals=. Unpack the OS X or Windows file as required, and copy all =.mxe= or =.mxo= files into =cassiel.zeroconf/externals=.

** Build

** Windows Issues

- You need to install Apple's Bonjour for Windows (known as Bonjour Print Services). Download link here:

  <http://support.apple.com/kb/dl999>

- The Zeroconf objects need a Visual C++ runtime library in order to work. Download link here:
  <http://www.microsoft.com/downloads/en/details.aspx?FamilyID=9b2da534-3e03-4391-8a4d-074b9f2bc1bf&displaylang=en&pf=true>

  We've also taken the liberty of including the installer package here (since it is, after all, "redistributable").

** OS X Issues

- I've made some slight mods to maxmspsdk.xcconfig - I plant `sdk-build' at the same level as `zeroconf' (rather than one level up). Also, there's an Info.plist for each project, rather than the common Cycling '74 one (with Cycling '74's copyright notice and other boilerplate).

- For both builds, put the `c74support' directory from the SDK into the same directory as `zeroconf' - I didn't want to put this into Github since it's big and rather untidy.

Nick Rothwell, nick@cassiel.com, 2011-05-20.

** Revision History

- 2011-05-20 :: Original maintenance port
- 2015-11-xx :: Revisit to prepare =zeroconf= for Max 7's Package Manager

** Credits

- Original code by Rémy Muller
- This maintenance port by Nick Rothwell, =nick@cassiel.com=
